# Generated by Django 4.2.10 on 2025-05-09 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("require_comment_approval", models.BooleanField(default=False)),
                ("allow_anonymous_comments", models.BooleanField(default=True)),
                ("notify_on_new_comments", models.BooleanField(default=True)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("session_timeout", models.IntegerField(default=60)),
                ("login_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=False)),
                ("notify_on_new_articles", models.BooleanField(default=True)),
                ("notify_on_replies", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diariamente"),
                            ("weekly", "Semanalmente"),
                            ("never", "Nunca"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("show_email", models.BooleanField(default=False)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("pt-BR", "Português (Brasil)"),
                            ("en-US", "English (US)"),
                            ("es", "Español"),
                        ],
                        default="pt-BR",
                        max_length=10,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Claro"),
                            ("dark", "Escuro"),
                            ("system", "Sistema"),
                        ],
                        default="dark",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user settings",
                "verbose_name_plural": "user settings",
            },
        ),
    ]
