# Generated by Django 4.2.10 on 2025-05-09 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_merge_20240523_1234"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
            },
        ),
    ]
