# Generated by Django 5.2.1 on 2025-05-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_create_social_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codigo_verificacao_sms',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_enviado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
