# Generated by Django 5.2.1 on 2025-05-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_codigo_verificacao_sms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='codigo_verificacao_sms',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sms_enviado_em',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefone_verificado',
        ),
    ]
