# Generated by Django 5.2.1 on 2025-05-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_options_and_more'),
    ]

    operations = [
    ]
