# Generated by Django 5.2.1 on 2025-05-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20250523_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telefone',
        ),
    ]
