# Generated by Django 5.2.1 on 2025-05-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_departamento_customuser_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='departamento',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cargo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='accounts.cargo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='departamento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='accounts.departamento'),
        ),
    ]
