# Generated by Django 5.2.1 on 2025-05-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_populate_cargo_departamento'),
    ]

    operations = [
        # Remover os campos antigos
        migrations.RemoveField(
            model_name='customuser',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='departamento',
        ),

        # Renomear os novos campos
        migrations.RenameField(
            model_name='customuser',
            old_name='cargo_fk',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='departamento_fk',
            new_name='departamento',
        ),
    ]
