# Generated by Django 5.2.1 on 2025-05-28 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('profile_update', 'Atualização de Perfil'), ('password_change', 'Alteração de Senha'), ('email_change', 'Alteração de Email'), ('group_change', 'Alteração de Grupos'), ('status_change', 'Alteração de Status'), ('create', 'Criação de Conta'), ('delete', 'Exclusão de Conta'), ('admin_action', 'Ação Administrativa')], max_length=20, verbose_name='Ação')),
                ('description', models.TextField(help_text='Descrição detalhada da ação realizada', max_length=500, verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, help_text='Informações do navegador/dispositivo', null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Usuário que executou a ação (para ações administrativas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL, verbose_name='Executado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atividade do Usuário',
                'verbose_name_plural': 'Atividades dos Usuários',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_us_user_id_5da0f6_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_us_action_ed4f0b_idx')],
            },
        ),
    ]
