# Generated by Django 5.2.1 on 2025-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codigo_ativacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='codigo_ativacao_criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tentativas_codigo',
            field=models.IntegerField(default=0),
        ),
    ]
