# Generated by Django 5.2.1 on 2025-05-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='slug',
            field=models.SlugField(blank=True, default='email-config', max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='socialproviderconfig',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='slug',
            field=models.SlugField(blank=True, default='system-config', max_length=60, unique=True),
        ),
    ]
