# Generated by Django 5.2.1 on 2025-05-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_emailconfig_slug_socialproviderconfig_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='ldap-config', max_length=60, unique=True)),
                ('port', models.IntegerField(default=389)),
                ('base_dn', models.CharField(max_length=255)),
                ('bind_dn', models.CharField(blank=True, max_length=255)),
                ('bind_password', models.CharField(blank=True, max_length=255)),
                ('search_filter', models.CharField(default='(objectClass=person)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração LDAP',
                'verbose_name_plural': 'Configurações LDAP',
            },
        ),
    ]
