# Generated by Django 5.2.1 on 2025-05-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_ldapconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='domain',
            field=models.CharField(blank=True, help_text='Domínio para criação de emails de usuários LDAP', max_length=255),
        ),
    ]
