# Generated by Django 5.2.1 on 2025-05-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_ldapconfig_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='server_uri',
            field=models.CharField(blank=True, help_text='URI completa do servidor LDAP (ex: ldap://servidor:389)', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='email_host_password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ldapconfig',
            name='bind_password',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
