# Generated by Django 5.2.1 on 2025-05-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_ldapconfig_server_uri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_core', models.BooleanField(default=False, help_text='Apps core não podem ser desativados')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de App',
                'verbose_name_plural': 'Configurações de Apps',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_app_management',
            field=models.BooleanField(default=True, help_text='Permite ativar/desativar módulos'),
        ),
    ]
