# Generated by Django 5.2.1 on 2025-05-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_environmentvariable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='Nome da configuração do banco', max_length=100)),
                ('slug', models.SlugField(blank=True, default='database-config', max_length=60, unique=True)),
                ('engine', models.CharField(choices=[('django.db.backends.sqlite3', 'SQLite'), ('django.db.backends.postgresql', 'PostgreSQL'), ('django.db.backends.mysql', 'MySQL'), ('django.db.backends.oracle', 'Oracle')], default='django.db.backends.sqlite3', max_length=100)),
                ('database_name', models.CharField(help_text='Nome do banco de dados ou caminho para SQLite', max_length=255)),
                ('host', models.CharField(blank=True, default='localhost', help_text='Host do servidor de banco', max_length=255)),
                ('port', models.IntegerField(blank=True, help_text='Porta do servidor (deixe vazio para padrão)', null=True)),
                ('user', models.CharField(blank=True, help_text='Usuário do banco de dados', max_length=255)),
                ('password', models.CharField(blank=True, help_text='Senha do banco de dados', max_length=500)),
                ('conn_max_age', models.IntegerField(default=0, help_text='Tempo máximo de vida da conexão em segundos')),
                ('conn_health_checks', models.BooleanField(default=False, help_text='Verificações de saúde da conexão')),
                ('ssl_require', models.BooleanField(default=False, help_text='Exigir conexão SSL')),
                ('ssl_ca', models.CharField(blank=True, help_text='Caminho para certificado CA SSL', max_length=500)),
                ('ssl_cert', models.CharField(blank=True, help_text='Caminho para certificado SSL', max_length=500)),
                ('ssl_key', models.CharField(blank=True, help_text='Caminho para chave SSL', max_length=500)),
                ('charset', models.CharField(blank=True, default='utf8mb4', help_text='Charset para MySQL', max_length=50)),
                ('atomic_requests', models.BooleanField(default=False, help_text='Usar transações atômicas')),
                ('autocommit', models.BooleanField(default=True, help_text='Auto-commit das transações')),
                ('test_database_name', models.CharField(blank=True, help_text='Nome do banco para testes', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Configuração ativa')),
                ('is_default', models.BooleanField(default=False, help_text='Configuração padrão do sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Banco de Dados',
                'verbose_name_plural': 'Configurações de Banco de Dados',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
