# Generated by Django 5.2.1 on 2025-05-26 17:17

import apps.config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_databaseconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon do site (ICO, PNG, JPG, SVG - máx. 1MB, 16x16 a 512x512px, preferencialmente quadrado)', null=True, upload_to='favicons/', validators=[apps.config.models.validate_favicon_image]),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='logo_principal',
            field=models.ImageField(blank=True, help_text='Logo principal do site (PNG, JPG, SVG, WEBP - máx. 5MB, 50x50 a 2000x2000px)', null=True, upload_to='logos/', validators=[apps.config.models.validate_logo_image]),
        ),
    ]
