# Generated by Django 5.2.1 on 2025-05-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_plugin_widget_systemconfig_accent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configbackup',
            name='app_configs',
            field=models.JSONField(default=dict, help_text='Configurações de apps'),
        ),
        migrations.AlterField(
            model_name='configbackup',
            name='database_configs',
            field=models.JSONField(default=dict, help_text='Configurações de banco'),
        ),
        migrations.AlterField(
            model_name='configbackup',
            name='email_configs',
            field=models.JSONField(default=dict, help_text='Configurações de email'),
        ),
        migrations.AlterField(
            model_name='configbackup',
            name='environment_variables',
            field=models.JSONField(default=dict, help_text='Variáveis de ambiente'),
        ),
        migrations.AlterField(
            model_name='configbackup',
            name='ldap_configs',
            field=models.JSONField(default=dict, help_text='Configurações LDAP'),
        ),
        migrations.AlterField(
            model_name='configbackup',
            name='social_configs',
            field=models.JSONField(default=dict, help_text='Configurações sociais'),
        ),
        migrations.AlterField(
            model_name='configbackup',
            name='system_config',
            field=models.JSONField(default=dict, help_text='Configurações do sistema'),
        ),
    ]
