# Generated by Django 5.2.1 on 2025-05-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_alter_configbackup_app_configs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='use_console_backend',
            field=models.BooleanField(default=False, help_text='Usar backend de console (desenvolvimento) - emails aparecerão no terminal em vez de serem enviados'),
        ),
    ]
