# Generated by Django 5.2.1 on 2025-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_add_console_backend_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Marcar como configuração padrão do sistema - aplicará automaticamente as configurações ao Django'),
        ),
    ]
