# Generated by Django 4.2.10 on 2025-05-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0002_manga_author_manga_favorites_manga_genres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="chapter_type",
            field=models.CharField(
                choices=[("images", "Imagens"), ("pdf", "PDF")],
                default="images",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="chapters/pdf/"),
        ),
    ]
