# Generated by Django 4.2.10 on 2025-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mangas", "0003_chapter_chapter_type_chapter_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="pdf_file_path",
            field=models.CharField(
                blank=True,
                help_text="Caminho para o arquivo PDF quando enviado em partes",
                max_length=255,
                null=True,
            ),
        ),
    ]
