# Generated by Django 5.2.5 on 2025-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_add_license_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodule',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
